# Generated by Django 3.1.5 on 2021-03-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0002_auto_20210315_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
