# Generated by Django 3.1.5 on 2021-04-21 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('phone2', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_customer_name', models.CharField(max_length=50)),
                ('order_product_name', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField()),
                ('order_per_product_price', models.IntegerField()),
                ('order_total_product_price', models.IntegerField()),
                ('order_date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_product_image', models.ImageField(blank=True, null=True, upload_to='sold_product_images/')),
                ('sold_product_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('sold_product_price_per_product', models.FloatField(blank=True, null=True)),
                ('sold_product_price', models.FloatField(blank=True, null=True)),
                ('total_sales_done', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('bar_code', models.ImageField(blank=True, null=True, upload_to='bar_code/')),
                ('total_product', models.IntegerField(default=0)),
                ('issue_quantity', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('discount_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('total_investment_made', models.IntegerField(blank=True, default=0, null=True)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(default=datetime.datetime.today)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dealerinformation')),
            ],
        ),
    ]
